In [1]:
import torch
import numpy as np
import pandas as pd
import random
import copy 
import time 

In [ ]:
# 先写麻烦的 那就是要确保流量不变性
# 确定一下流量的比例 到底这个初始的流量比例占百分之多少 然后输出一下
# 把mac_sev s_cpu s_mem totoal_cpu total_mem 读进来 其实最简单的办法就是把mac_sev的每一种服务增加一下 然后直到物理机容量增加

In [ ]:
def test(total_cpu, total_mem, s_cpu, s_mem, mac_trf, trf_cpu_mem, mac_sev, sev_trf_in, sev_trf_out, sev_trf):
    # total cpu == now all
    # mac cpu == input mac cpu && now all
    # sev_trf == ?
    # mac_trf
    # com p == now all p_cpu and p_mem
    m_c = np.dot(mac_sev, s_cpu)
    m_m = np.dot(mac_sev, s_mem)
    print(m_c)
    print(m_m)
    print(np.allclose(m_c, trf_cpu_mem[: , 1]))
    print(np.allclose(m_m, trf_cpu_mem[: , 4]))
    p_c = m_c / total_cpu
    p_m = m_m / total_mem
    print(p_c)
    print(p_m)
    print(np.allclose(p_c, trf_cpu_mem[:, 3]))
    print(np.allclose(p_m, trf_cpu_mem[:, 6]))
    m_t = np.zeros(mac_sev.shape[0])
    for a in range(mac_sev.shape[0]):
        for b in range(mac_sev.shape[1] - 1):
            for c in range(b + 1, mac_sev.shape[1]):
                m_t[a] += min(sev_trf_out[b][c] * mac_sev[a][b], sev_trf_in[b][c] * mac_sev[a][c])
    print(np.allclose(m_t, mac_trf))
    a = np.dot(sev_trf_in, mac_sev.sum(axis = 0)
    b = sev_trf_out * mac_sev.sum(axis = 0)


# 这是分布不同

## mac_sev, now_all, mac_trf, mac_cpu, mac_mem

### VT_1 

In [21]:
ll_path = "../"
rank_name = ll_path + 'rank.txt'

VT_name = 1

rank_array = np.loadtxt(rank_name, dtype=np.float32, delimiter=',')
rank = int(rank_array[2])

##reward_kind_name = 'reward.txt'
#with open(reward_kind_name, 'r') as f:
#    reward_kind = f.read()

filename = ll_path + 'data' + str(rank) + '/'
dot = '.npy'
mac_kind = int(rank_array[0])
sev_kind = int(rank_array[1])

#####################
#VT_1mac_sev_10_80
mac_sev_name = 'VT_' + str(VT_name) + 'mac_sev' + '_' + \
    str(mac_kind) + '_' + str(sev_kind)
mac_trf_name = 'VT_' + str(VT_name) + 'mac_trf' + '_' + \
    str(mac_kind) + '_' + str(sev_kind) 

sev_trf_name = 'sev_trf' + '_' + str(sev_kind) + '_' + str(rank)  # 后面可以补充字符串说明
sev_trf_out_name = 'sev_trf_out' + '_' + \
    str(sev_kind) + '_' + str(rank)  # 后面可以补充字符串说明
sev_trf_in_name = 'sev_trf_in' + '_' + \
    str(sev_kind) + '_' + str(rank)  # 后面可以补充字符串说明
sev_cpu_name = 'sev_cpu' + '_' + str(sev_kind) + '_' + str(rank)
sev_mem_name = 'sev_mem' + '_' + str(sev_kind) + '_' + str(rank) 

####################
# mac_cpu_name = 'mac_cpu' + '_' + str(mac_kind) + '_' + str(rank)
# mac_mem_name = 'mac_mem' + '_' + str(mac_kind) + '_' + str(rank)

total_cpu_name = 'total_cpu' + '_' + str(mac_kind) + '_' + str(rank)
total_mem_name = 'total_mem' + '_' + str(mac_kind) + '_' + str(rank)

############################
mac_sev_cpu_name = 'VT_' + str(VT_name) + 'mac_sev_cpu'  + \
    str(mac_kind) + '_' + str(sev_kind)
mac_sev_mem_name = 'VT_' + str(VT_name) + 'mac_sev_mem'  + \
    str(mac_kind) + '_' + str(sev_kind)
now_all_name = 'VT_' + str(VT_name) + 'now_all' + '_' + str(mac_kind) + '_' + str(sev_kind)

trf_cpu_mem = np.load(filename + now_all_name + dot)
mac_sev_cpu = np.load(filename + mac_sev_cpu_name + dot)
mac_sev_mem = np.load(filename + mac_sev_mem_name + dot)
mac_sev = np.load(filename + mac_sev_name + dot)
sev_trf = np.load(filename + sev_trf_name + dot)
sev_trf_out = np.load(filename + sev_trf_out_name + dot)
sev_trf_in = np.load(filename + sev_trf_in_name + dot)

# mac_cpu = np.load(filename + mac_cpu_name + dot)
# mac_mem = np.load(filename + mac_mem_name + dot)
total_cpu = np.load(filename + total_cpu_name + dot)
total_mem = np.load(filename + total_mem_name + dot)


s_cpu = np.load(filename + sev_cpu_name + dot)
s_mem = np.load(filename + sev_mem_name + dot)
stop = np.zeros(mac_sev.shape[0]).reshape((mac_sev.shape[0], 1))
trf_cpu_mem = np.concatenate((trf_cpu_mem, stop), axis=1)


print(trf_cpu_mem.shape)
print(mac_sev_cpu.shape)
print(mac_sev_mem.shape)
print(mac_sev.shape)
print(sev_trf.shape)
print(sev_trf_out.shape)
print(sev_trf_in.shape)
# print(mac_cpu.shape)
# print(mac_mem.shape)
print(total_cpu.shape)
print(total_mem.shape)

(10, 8)
(10, 80)
(10, 80)
(10, 80)
(80, 80)
(80, 80)
(80, 80)
(10,)
(10,)


In [23]:
m_s = np.dot(mac_sev, s_cpu)
m_s == trf_cpu_mem[:, 1]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [58]:
mac_sev.sum(axis= 0)

array([1., 2., 2., 3., 1., 3., 5., 6., 1., 8., 1., 3., 1., 6., 2., 4., 5.,
       5., 2., 3., 2., 1., 4., 8., 7., 2., 5., 1., 6., 6., 5., 3., 5., 9.,
       3., 4., 3., 1., 4., 3., 8., 2., 2., 3., 4., 3., 7., 3., 2., 1., 3.,
       3., 3., 1., 2., 1., 2., 2., 1., 5., 4., 3., 2., 5., 5., 7., 4., 6.,
       4., 1., 3., 4., 3., 3., 3., 5., 3., 5., 4., 2.])

In [54]:
tmp = mac_sev.sum(axis = 0).reshape((mac_sev.shape[1], 1))
a = mac_sev.sum(axis= 0) * sev_trf_in
b = sev_trf_out * tmp 

In [40]:
c = np.ones((80,80))

In [50]:
b

array([[   0.,    0.,  238., ...,  192.,  188.,    0.],
       [   0.,    0.,  154., ...,  120.,   56.,  176.],
       [   0.,    0.,    0., ...,    0.,  176.,   72.],
       ...,
       [   0.,    0.,    0., ...,    0., 1160., 1220.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [55]:
a

array([[   0.,    0.,  272., ..., 1280.,  752.,    0.],
       [   0.,    0.,  242., ..., 1100.,  308.,  484.],
       [   0.,    0.,    0., ...,    0.,  616.,  126.],
       ...,
       [   0.,    0.,    0., ...,    0.,  696.,  366.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [61]:
sev_trf_in[0][2] 

136.0

In [60]:
sev_trf_out[0][2]

238.0

In [62]:
sev_trf[0][2] / sev_trf_out[0][2]

4.0

## 1

In [161]:
re_mac_sev1 = gen_mac_sev(mac_kind, sev_kind, 0, 2, 0.4, 0.4)
m, n, mac_cpu1, mac_mem1 = com_cpu_mem(total_cpu, total_mem, s_cpu, s_mem, re_mac_sev1, mac_kind)
re_mac_trf_1 = compute_mac_trf(mac_kind, sev_kind, re_mac_sev1, sev_trf_out, sev_trf_in)
total_tcm_1 = gtotal_and_now_cpumem(mac_cpu1, total_cpu, mac_mem1, total_mem, re_mac_trf_1)
m_s_c1, m_s_m1 = gen_ms_cpu_mem(mac_kind, sev_kind, re_mac_sev1, s_cpu, s_mem)
print(np.mean(total_tcm_1[:,3]))
print(np.mean(total_tcm_1[:,-1]))

[0.37273259 0.35342305 0.36102984 0.27520967 0.28730252 0.29568646
 0.23283859 0.23144712 0.18413729 0.20106679]
[0.35338949 0.418572   0.35218612 0.25070197 0.26333734 0.38576598
 0.3490953  0.28709288 0.23232811 0.20699638]
[1911. 1812. 1851. 1411. 1473. 1275. 1004.  998.  794.  867.]
[1762. 2087. 1756. 1250. 1313. 1599. 1447. 1190.  963.  858.]
mac < total? True True
0.27948739312736637
0.3099465572360147


In [173]:
np.save(path + 'VT_1mac_sev_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', re_mac_sev1)
np.save(path + 'VT_1mac_trf_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', re_mac_trf_1)
np.save(path + 'VT_1now_all_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', total_tcm_1)
np.save(path + 'VT_1mac_sev_cpu' + str(mac_kind) + '_' + str(sev_kind) + '.npy', m_s_c1)
np.save(path + 'VT_1mac_sev_mem' + str(mac_kind) + '_' + str(sev_kind) + '.npy', m_s_m1)

## 2

In [164]:
re_mac_sev2 = gen_mac_sev(mac_kind, sev_kind, 0, 3, 0.4, 0.14)
m, n, mac_cpu2, mac_mem2 = com_cpu_mem(total_cpu, total_mem, s_cpu, s_mem, re_mac_sev2, mac_kind)
re_mac_trf_2 = compute_mac_trf(mac_kind, sev_kind, re_mac_sev2, sev_trf_out, sev_trf_in)
total_tcm_2 = gtotal_and_now_cpumem(mac_cpu2, total_cpu, mac_mem2, total_mem, re_mac_trf_2)
m_s_c2, m_s_m2 = gen_ms_cpu_mem(mac_kind, sev_kind, re_mac_sev2, s_cpu, s_mem)
print(np.mean(total_tcm_2[:,3]))
print(np.mean(total_tcm_2[:,-1]))

[0.46069826 0.59371952 0.72791106 0.73083675 0.50731422 0.68923933
 0.72912801 0.82722635 0.75440631 0.83998145]
[0.53590052 0.55595668 0.64781388 0.68070598 0.62815884 0.66224367
 0.63763571 0.85548854 0.81881785 0.77297949]
[2362. 3044. 3732. 3747. 2601. 2972. 3144. 3567. 3253. 3622.]
[2672. 2772. 3230. 3394. 3132. 2745. 2643. 3546. 3394. 3204.]
mac < total? True True
0.6860461259880302
0.6795701159870073


In [174]:
np.save(path + 'VT_2mac_sev_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', re_mac_sev2)
np.save(path + 'VT_2mac_trf_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', re_mac_trf_2)
np.save(path + 'VT_2now_all_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', total_tcm_2)
np.save(path + 'VT_2mac_sev_cpu' + str(mac_kind) + '_' + str(sev_kind) + '.npy', m_s_c2)
np.save(path + 'VT_2mac_sev_mem' + str(mac_kind) + '_' + str(sev_kind) + '.npy', m_s_m2)

## 3

In [168]:
re_mac_sev3 = gen_mac_sev(mac_kind, sev_kind, 0, 3, 0.2, 0.17)
m, n, mac_cpu3, mac_mem3 = com_cpu_mem(total_cpu, total_mem, s_cpu, s_mem, re_mac_sev3, mac_kind)
re_mac_trf_3 = compute_mac_trf(mac_kind, sev_kind, re_mac_sev3, sev_trf_out, sev_trf_in)
total_tcm_3 = gtotal_and_now_cpumem(mac_cpu3, total_cpu, mac_mem3, total_mem, re_mac_trf_3)
m_s_c3, m_s_m3 = gen_ms_cpu_mem(mac_kind, sev_kind, re_mac_sev3, s_cpu, s_mem)
print(np.mean(total_tcm_3[:,3]))
print(np.mean(total_tcm_3[:,-1]))

[0.98244587 0.75931344 0.76106885 0.72693583 0.96391652 0.89030612
 0.88265306 0.88961039 0.85876623 1.13172542]
[0.81989571 0.74468512 0.86181308 0.80365022 0.80244685 1.08178528
 0.82243667 0.89264174 0.97973462 0.92159228]
[5037. 3893. 3902. 3727. 4942. 3839. 3806. 3836. 3703. 4880.]
[4088. 3713. 4297. 4007. 4001. 4484. 3409. 3700. 4061. 3820.]
mac < total? False False
0.8846741739410803
0.8730681565802824


In [175]:
np.save(path + 'VT_3mac_sev_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', re_mac_sev3)
np.save(path + 'VT_3mac_trf_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', re_mac_trf_3)
np.save(path + 'VT_3now_all_' + str(mac_kind) + '_' + str(sev_kind) + '.npy', total_tcm_3)
np.save(path + 'VT_3mac_sev_cpu' + str(mac_kind) + '_' + str(sev_kind) + '.npy', m_s_c3)
np.save(path + 'VT_3mac_sev_mem' + str(mac_kind) + '_' + str(sev_kind) + '.npy', m_s_m3)

## 流量变化 分布不变

In [4]:
ll_path = "../"
rank_name = ll_path + 'rank.txt'
CT_name = 3
rank_array = np.loadtxt(rank_name, dtype=np.float32, delimiter=',')
rank = int(rank_array[2])

#reward_kind_name = 'reward.txt'
##with open(reward_kind_name, 'r') as f:
#    reward_kind = f.read()

filename = ll_path + 'data' + str(rank) + '/'
dot = '.npy'
mac_kind = int(rank_array[0])
sev_kind = int(rank_array[1])


mac_sev_name = 'mac_sev' + '_' + \
    str(mac_kind) + '_' + str(sev_kind) + '_' + str(rank)

###
mac_trf_name = 'CT' + str(CT_name) + '_' + 'mac_trf' + \
    str(mac_kind) + '_' + str(sev_kind)
sev_trf_name = 'CT' + str(CT_name) + '_' + 'sev_trf'  + str(mac_kind) + '_' + str(sev_kind)  # 后面可以补充字符串说明
sev_trf_out_name = 'CT' + str(CT_name) + '_' + 'sev_trf_out' +  str(mac_kind) + '_' + \
    str(sev_kind)
sev_trf_in_name = 'CT' + str(CT_name) + '_' +'sev_trf_in' +  str(mac_kind) + '_' + \
    str(sev_kind)



sev_cpu_name = 'sev_cpu' + '_' + str(sev_kind) + '_' + str(rank)
sev_mem_name = 'sev_mem' + '_' + str(sev_kind) + '_' + str(rank)
mac_cpu_name = 'mac_cpu' + '_' + str(mac_kind) + '_' + str(rank)
mac_mem_name = 'mac_mem' + '_' + str(mac_kind) + '_' + str(rank)
total_cpu_name = 'total_cpu' + '_' + str(mac_kind) + '_' + str(rank)
total_mem_name = 'total_mem' + '_' + str(mac_kind) + '_' + str(rank)
mac_sev_cpu_name = 'mac_sev_cpu' + '_' + \
    str(mac_kind) + '_' + str(sev_kind) + '_' + str(rank)
mac_sev_mem_name = 'mac_sev_mem' + '_' + \
    str(mac_kind) + '_' + str(sev_kind) + '_' + str(rank)
now_all_name = 'CT' + str(CT_name) + '_' + 'now_all' + str(mac_kind) + '_' + str(sev_kind)

trf_cpu_mem = np.load(filename + now_all_name + dot)
mac_sev_cpu = np.load(filename + mac_sev_cpu_name + dot)
mac_sev_mem = np.load(filename + mac_sev_mem_name + dot)
mac_sev = np.load(filename + mac_sev_name + dot)
sev_trf = np.load(filename + sev_trf_name + dot)
sev_trf_out = np.load(filename + sev_trf_out_name + dot)
sev_trf_in = np.load(filename + sev_trf_in_name + dot)

s_cpu = np.load(filename + sev_cpu_name + dot)
s_mem = np.load(filename + sev_mem_name + dot)
stop = np.zeros(mac_sev.shape[0]).reshape((mac_sev.shape[0], 1))
trf_cpu_mem = np.concatenate((trf_cpu_mem, stop), axis=1)

topk = 0  # np.loadtxt('line2.csv', delimiter=",")


print(trf_cpu_mem.shape)
print(mac_sev_cpu.shape)
print(mac_sev_mem.shape)
print(mac_sev.shape)
print(sev_trf.shape)
print(sev_trf_out.shape)
print(sev_trf_in.shape)

np.savetxt(ll_path + str(mac_kind) + '_' + str(sev_kind) + '/' + sev_trf_name + '.csv', sev_trf, delimiter=',')
np.savetxt(ll_path + str(mac_kind) + '_' + str(sev_kind) + '/' + sev_trf_in_name + '.csv', sev_trf_in, delimiter=',')
np.savetxt(ll_path + str(mac_kind) + '_' + str(sev_kind) + '/' + sev_trf_out_name + '.csv', sev_trf_out, delimiter=',')

(20, 8)
(20, 100)
(20, 100)
(20, 100)
(100, 100)
(100, 100)
(100, 100)


In [11]:
sev_trf 

array([[  0.,   0., 624., ..., 390.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0., 198.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [12]:
a = mac_sev.sum(axis = 0) * sev_trf_in
b = sev_trf_out * mac_sev.sum(axis = 0).reshape((mac_sev.shape[1], 1))

In [13]:
print(np.allclose(a,b))
print(np.allclose(a, sev_trf))

True
True


## 1

In [77]:
s1 = gen_sev_trf(sev_kind, 100, 1000, sev_trf, 0, 0.25)
sev_trf_1, sev_trf_out_1, sev_trf_in_1 = gen_sev_trf_out_and_in(s1, mac_sev, sev_kind, lcm)
mt1 = compute_mac_trf(mac_kind, sev_kind, mac_sev, sev_trf_out_1, sev_trf_in_1)
now_all1 = gtotal_and_now_cpumem(mac_cpu, total_cpu, mac_mem, total_mem, mt1)
np.save(path + 'CT1_sev_trf' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_1)
np.save(path + 'CT1_sev_trf_out' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_out_1)
np.save(path + 'CT1_sev_trf_in' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_in_1)
np.save(path + 'CT1_mac_trf' + str(mac_kind) + '_' + str(sev_kind) + '.npy', mt1)
np.save(path + 'CT1_now_all' + str(mac_kind) + '_' + str(sev_kind) + '.npy', now_all1)

流量利用率为0.615506329113924
流量利用率为0.30390625


## 2

In [79]:
s2 = gen_sev_trf(sev_kind, 100, 1000, sev_trf, 0, 0.5)
sev_trf_2, sev_trf_out_2, sev_trf_in_2 = gen_sev_trf_out_and_in(s2, mac_sev, sev_kind, lcm)
mt2 = compute_mac_trf(mac_kind, sev_kind, mac_sev, sev_trf_out_2, sev_trf_in_2)
now_all2 = gtotal_and_now_cpumem(mac_cpu, total_cpu, mac_mem, total_mem, mt2)
np.save(path + 'CT2_sev_trf' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_2)
np.save(path + 'CT2_sev_trf_out' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_out_2)
np.save(path + 'CT2_sev_trf_in' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_in_2)
np.save(path + 'CT2_mac_trf' + str(mac_kind) + '_' + str(sev_kind) + '.npy', mt2)
np.save(path + 'CT2_now_all' + str(mac_kind) + '_' + str(sev_kind) + '.npy', now_all2)

流量利用率为0.41107594936708863
流量利用率为0.20296875


## 3

In [82]:
s3 = gen_sev_trf(sev_kind, 100, 1000, sev_trf, 0, 0.75)
sev_trf_3, sev_trf_out_3, sev_trf_in_3 = gen_sev_trf_out_and_in(s3, mac_sev, sev_kind, lcm)
mt3 = compute_mac_trf(mac_kind, sev_kind, mac_sev, sev_trf_out_3, sev_trf_in_3)
now_all3 = gtotal_and_now_cpumem(mac_cpu, total_cpu, mac_mem, total_mem, mt3)
np.save(path + 'CT3_sev_trf' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_3)
np.save(path + 'CT3_sev_trf_out' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_out_3)
np.save(path + 'CT3_sev_trf_in' + str(mac_kind) + '_' + str(sev_kind) + '.npy', sev_trf_in_3)
np.save(path + 'CT3_mac_trf' + str(mac_kind) + '_' + str(sev_kind) + '.npy', mt3)
np.save(path + 'CT3_now_all' + str(mac_kind) + '_' + str(sev_kind) + '.npy', now_all3)

流量利用率为0.20537974683544305
流量利用率为0.10140625
